export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as CompanyLogos } from './CompanyLogos'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'